config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  #get 'pages/index'
  get "/contacts", to: 'pages#contacts'
  root to: "pages#index"
  
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save {self.email = email.downcase}

    validates :name, presence: true, length:{ maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true    
    
    has_secure_password 
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true 

    # Returns the hash digest of the given string.

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contacts
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      # Create an error message.
      flash.now[:danger] = "invalid user name or password please try again"
      render 'new'
    end
  end


    def destroy
      log_out if logged_in?
      redirect_to root_url
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update]
    before_action :correct_user, only: [:edit, :update]
    before_action :admin_user, only: :destroy

    def index
        @users = User.paginate(page: params[:page])
    end 
    
    def show
        @user = User.find(params[:id])
    end 

    def new
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)

        if @user.save 
            log_in @user
            flash[:success] = " Welcome to the page! "
            redirect_to @user 
        else 
            render 'new'
        end 
    end 

    def edit 
        @user = User.find(params[:id])
    end 

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = " Your details were updated "
            redirect_to @user 
        else
            render 'edit'
    end

    end 

    # destrying a user 
    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "User deleted successfuly!"
        redirect_to users_url
    end

    # Confirms an admin user.
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

    private 
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end 

    def logged_in_user
        unless logged_in?
            store_location
            flash[:danger] = "Please log in to perform this action."
            redirect_to login_url
        end
    end

    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
    end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    # Remembers a user in a persistent session.
    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

   # Returns the user corresponding to the remember token cookie.
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.encrypted[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end 
    end

    # Forgets a persistent session.
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user?(user)
        user && user == current_user
    end

    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        size = options[:size]
        gravatar_id = Digest:: MD5:: hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end 
end 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  partial: "shared/banner"%>
    <%= render  partial: "shared/navbar"%>
    <div class = "container">
      <%flash.each do |message_type, message|%>
        <div class="alert alert-<%= message_type%> errors"><%= message%><button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></div>  
      <%end%>

      <%= yield %>
        <%= debug(params) if Rails.env.development? %>
  </div>
      
        <%= render partial: "shared/footer"%>
  </body>

</html>

app/views/pages/contacts.html.erb
<% provide(:title, 'contacts') %>

<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/index.html.erb
<% provide(:title, 'Home') %>


<!-- stat of carousel-->

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag("1.jpg", class: "d-block w-100")%>
      <div class="carousel-caption d-none d-md-block">
        <%= link_to "Sign up Now", signup_path, class: "btn btn-primary"%> 
        <h2>Sign Up Now and Request Your Design</h5>
        <p>We have a team of hihgly qulified professionals who can design and estimate your projects.</p>
      </div>
    </div>
    <div class="carousel-item">
    <%= image_tag("2.jpg", class: "d-block w-100")%>
      
    </div>
    <div class="carousel-item">
      <%= image_tag("3.jpg", class: "d-block w-100")%>
     
    </div>
  </div>
 

</div>

<!-- end of carousel -->

app/views/shared/_banner.html.erb
<div class="banner">
<div class="container">

<div class="row">
  <div class="col-6">Phone: 0450442424</div>
  <div class="col-4 text"> <span>Follow us on Social Media</span></div>
 
  <div class= "col-2">
  <i class="fab fa-facebook-square"></i>    
  <i class="fab fa-instagram"></i>
  <i class="fab fa-twitter-square"></i>
</div>
</div>
</div>
</div>

app/views/shared/_error_messages.erb
    <% if @user.errors.any?%>
        
        <div class ="alert alert-danger" role= "alert" >
        
            <div>
                The form contains <%= pluralize(@user.errors.count, "error")%>.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </div>
            <ul>
            
                <%@user.errors.full_messages.each do |msg|%>
                    
                    <li><%= msg%></li>
                <%end%>
            </ul>
        </div>

    <%end%>


   

app/views/shared/_footer.html.erb
<div class="footer">
    
</div>

app/views/shared/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: @user %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light ml-auto">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact Us", contacts_path, class: "nav-link"%>
      </li>
      <% if logged_in?%>
        <li class ="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
      <%end%>

      <!-- drop down menu bar-->
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item"><%= link_to "Settings", edit_user_path(current_user) %></a>
           
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"> <%= link_to "Log out", logout_path, method: :delete %></a>
          </div>
        </li>
        
        <% else %>
        
          <%= link_to "Sign up", signup_path, class: "btn btn-outline-primary"%> 
          <%= link_to "Log in", login_path, class: "btn btn-outline-primary "%>
        
        <% end %>
     
    </ul>
    
  </div>
</nav>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
        <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "delete", user, method: :delete,
            data: { confirm: "You sure?" } %>
        <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>


<div class="form-card">
    <h1>Update your profile</h1>
    <div>
        <%= render 'shared/form' %>
        <div class="gravatar_edit form-card">
            <%= gravatar_for @user %>
            <a href="https://gravatar.com/emails" target="_blank">Change</a>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 class="text-center">All users</h1>

<%= will_paginate %>
    <ul class="users">
        <%= render @users %>
    </ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>


<div class="form-card">
    <h1>Sign up</h1>
    <div>
        <%= render 'shared/form' %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class= "row">
    <aside class ="col-md-4"
        <section class="user_info">
            <h1>
                <%= gravatar_for @user%>
                <%= @user.name%>
            </h1>
        </section>
    </aside>
</div>